name: PR Checks

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  statuses: write
  checks: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test
        env:
          CI: true

      - name: Run linting
        run: yarn lint

  validate-typescript:
    name: TypeScript Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: TypeScript Check
        run: yarn tsc --noEmit

  analyze-dependencies:
    name: Dependency Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for vulnerabilities
        run: yarn audit
        continue-on-error: true # Don't fail the build on vulnerabilities, just report them

  comment-pr-status:
    name: Comment PR Status
    runs-on: ubuntu-latest
    needs: [build-and-test, validate-typescript, analyze-dependencies]
    if: always() # Run even if previous jobs have failed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate PR Comment
        id: pr-comment
        uses: actions/github-script@v6
        env:
          BUILD_STATUS: ${{ needs.build-and-test.result }}
          TS_STATUS: ${{ needs.validate-typescript.result }}
          DEP_STATUS: ${{ needs.analyze-dependencies.result }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildStatus = process.env.BUILD_STATUS;
            const tsStatus = process.env.TS_STATUS;
            const depStatus = process.env.DEP_STATUS;

            function getStatusEmoji(status) {
              switch(status) {
                case 'success': return '✅';
                case 'failure': return '❌';
                case 'cancelled': return '⚠️';
                default: return '⚠️';
              }
            }

            const statusTable = `
            | Check | Status |
            | ----- | ------ |
            | Build and Test | ${getStatusEmoji(buildStatus)} |
            | TypeScript Validation | ${getStatusEmoji(tsStatus)} |
            | Dependency Analysis | ${getStatusEmoji(depStatus)} |
            `;

            const allPassed = buildStatus === 'success' && tsStatus === 'success';
            const conclusion = allPassed 
              ? '✨ All required checks have passed!' 
              : '⚠️ Some checks have failed. Please review the issues above.';

            const comment = `## PR Check Results

            ${statusTable}

            ${conclusion}

            *Automated comment from GitHub Actions*
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
